// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5nrw8Y1TyHLpB-UHPA7vBO2DZV_vt7nA',
    appId: '1:525871552948:web:bfded38005fa2a658b7ae1',
    messagingSenderId: '525871552948',
    projectId: 'fir-project-a1eae',
    authDomain: 'fir-project-a1eae.firebaseapp.com',
    storageBucket: 'fir-project-a1eae.firebasestorage.app',
    measurementId: 'G-YPTZXC0BRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOY-v_YwrH2dMsnd9pzwPPg_Sd6i52x3A',
    appId: '1:525871552948:android:19eae50f0b7bae7d8b7ae1',
    messagingSenderId: '525871552948',
    projectId: 'fir-project-a1eae',
    storageBucket: 'fir-project-a1eae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxAcXdgM0YD_366l1Db5yjED-DeCtDHRA',
    appId: '1:525871552948:ios:35e46032bddbcf638b7ae1',
    messagingSenderId: '525871552948',
    projectId: 'fir-project-a1eae',
    storageBucket: 'fir-project-a1eae.firebasestorage.app',
    iosBundleId: 'com.example.liveScore',
  );
}
